-- 1. Asegurar campo firmado en proyectos
ALTER TABLE public.proyectos 
ADD COLUMN IF NOT EXISTS firmado BOOLEAN DEFAULT false;

-- 2. Crear tabla de protocolos
CREATE TABLE IF NOT EXISTS public.protocolos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Extender proyectos con datos de protocolo
ALTER TABLE public.proyectos 
ADD COLUMN IF NOT EXISTS protocolo_id BIGINT REFERENCES public.protocolos(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS folio INTEGER;

-- 4. Agregar soporte para cliente temporal o manual en citas
ALTER TABLE public.citas 
ADD COLUMN IF NOT EXISTS cliente_nombre_manual TEXT,
ADD COLUMN IF NOT EXISTS cliente_telefono_manual TEXT;

-- 5. CORRECCIÓN: Agregar columnas faltantes a la tabla de transacciones
-- Nota: proyecto_id y cliente_id deben ser tipo UUID en la base de datos para que no de error
ALTER TABLE public.transacciones
ADD COLUMN IF NOT EXISTS proyecto_id UUID REFERENCES public.proyectos(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS cliente_id UUID REFERENCES public.clientes(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS clave_xml TEXT,
ADD COLUMN IF NOT EXISTS iva_tarifa NUMERIC DEFAULT 0.13,
ADD COLUMN IF NOT EXISTS retencion NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS es_deducible BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS aceptado_hacienda BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS estado_pago TEXT DEFAULT 'Cobrado',
ADD COLUMN IF NOT EXISTS vencimiento DATE;
