-- SGIN PRO: Esquema de Base de Datos para Supabase (PostgreSQL)
-- Matriz Contable de Costa Rica y Gestión de Proyectos

-- 1. Clientes
CREATE TABLE IF NOT EXISTS public.clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    cedula TEXT,
    telefono TEXT,
    correo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Proyectos
CREATE TABLE IF NOT EXISTS public.proyectos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE CASCADE,
    firmado BOOLEAN DEFAULT false,
    tipo TEXT NOT NULL,
    costo NUMERIC DEFAULT 0,
    adelanto NUMERIC DEFAULT 0,
    numero_contrato TEXT,
    fecha_contrato DATE,
    tiene_iva BOOLEAN DEFAULT false,
    estado TEXT DEFAULT 'Pendiente Firma',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Presentaciones (Trámites)
CREATE TABLE IF NOT EXISTS public.presentaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto_id BIGINT REFERENCES public.proyectos(id) ON DELETE CASCADE,
    nombre TEXT NOT NULL,
    estado TEXT DEFAULT 'Catastro',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Transacciones (Unificado: Ingresos CXC y Egresos CXP)
CREATE TABLE IF NOT EXISTS public.transacciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion TEXT NOT NULL,
    monto NUMERIC NOT NULL,
    tipo TEXT NOT NULL, -- 'Ingreso' o 'Gasto'
    categoria TEXT,
    fecha DATE NOT NULL,
    subtotal NUMERIC DEFAULT 0,
    iva NUMERIC DEFAULT 0,
    metodo_pago TEXT,
    -- Campos extendidos para Matriz Contable Costa Rica
    clave_xml TEXT,
    iva_tarifa NUMERIC DEFAULT 0.13,
    retencion NUMERIC DEFAULT 0,
    es_deducible BOOLEAN DEFAULT true,
    aceptado_hacienda BOOLEAN DEFAULT true,
    estado_pago TEXT DEFAULT 'Cobrado', -- 'Cobrado', 'Pendiente', 'Pagado'
    vencimiento DATE,
    proyecto_id BIGINT REFERENCES public.proyectos(id) ON DELETE SET NULL,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Gastos Fijos
CREATE TABLE IF NOT EXISTS public.gastos_fijos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    monto NUMERIC NOT NULL,
    dia_cobro INTEGER DEFAULT 1,
    estado TEXT DEFAULT 'Activo',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Citas (Agenda)
CREATE TABLE IF NOT EXISTS public.citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    descripcion TEXT,
    fecha_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Activos (Inventario y Depreciación)
CREATE TABLE IF NOT EXISTS public.activos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    marca TEXT,
    modelo TEXT,
    serie TEXT,
    fecha_compra DATE,
    valor NUMERIC DEFAULT 0,
    estado TEXT DEFAULT 'Operativo',
    vida_util INTEGER DEFAULT 60, -- Vida útil en meses para cálculo de depreciación
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
