-- 1. Asegurar campo firmado en proyectos
ALTER TABLE public.proyectos 
ADD COLUMN IF NOT EXISTS firmado BOOLEAN DEFAULT false;

-- 2. Crear tabla de protocolos
CREATE TABLE IF NOT EXISTS public.protocolos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Extender proyectos con datos de protocolo
ALTER TABLE public.proyectos 
ADD COLUMN IF NOT EXISTS protocolo_id BIGINT REFERENCES public.protocolos(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS folio INTEGER;

-- 4. Crear tabla de usuarios
CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario TEXT NOT NULL UNIQUE,
    nombre TEXT NOT NULL,
    password TEXT NOT NULL,
    rol TEXT NOT NULL DEFAULT 'normal', -- 'admin' o 'normal'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Insertar usuarios por defecto del sistema
INSERT INTO public.usuarios (usuario, nombre, password, rol)
VALUES 
('207150846', 'Walter', 'Lusoma93*', 'admin'),
('Lusoma', 'Jessica (Admin)', 'Guitaras93*', 'admin'),
('Visitante', 'Visitante General', 'Visitante123', 'normal')
ON CONFLICT (usuario) DO NOTHING;

-- 6. Agregar soporte para cliente temporal o manual en citas
ALTER TABLE public.citas 
ADD COLUMN IF NOT EXISTS cliente_nombre_manual TEXT,
ADD COLUMN IF NOT EXISTS cliente_telefono_manual TEXT;

-- 7. Asegurar que las columnas proyecto_id y cliente_id existan en transacciones
ALTER TABLE public.transacciones
ADD COLUMN IF NOT EXISTS proyecto_id BIGINT REFERENCES public.proyectos(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS cliente_id BIGINT REFERENCES public.clientes(id) ON DELETE SET NULL;
